// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDhRCOvffEGAUOnzM4qjpJuashtUzPNKo',
    appId: '1:462679129561:web:301959c02e15e92dbf6dc8',
    messagingSenderId: '462679129561',
    projectId: 'manager-flutter-project',
    authDomain: 'manager-flutter-project.firebaseapp.com',
    storageBucket: 'manager-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5soyNeEop2io1lwUmjoRc_d7Y3uWOe64',
    appId: '1:462679129561:android:3ef2ae6771c33bb4bf6dc8',
    messagingSenderId: '462679129561',
    projectId: 'manager-flutter-project',
    storageBucket: 'manager-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlmI_c0_MwNzwoeKCaHtX4f8_Dk_C1HE',
    appId: '1:462679129561:ios:55e337a2d9adf722bf6dc8',
    messagingSenderId: '462679129561',
    projectId: 'manager-flutter-project',
    storageBucket: 'manager-flutter-project.appspot.com',
    iosClientId: '462679129561-o02qvmterq9g6dg2kj5mb9gnh245ub87.apps.googleusercontent.com',
    iosBundleId: 'com.hello.manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlmI_c0_MwNzwoeKCaHtX4f8_Dk_C1HE',
    appId: '1:462679129561:ios:55e337a2d9adf722bf6dc8',
    messagingSenderId: '462679129561',
    projectId: 'manager-flutter-project',
    storageBucket: 'manager-flutter-project.appspot.com',
    iosClientId: '462679129561-o02qvmterq9g6dg2kj5mb9gnh245ub87.apps.googleusercontent.com',
    iosBundleId: 'com.hello.manager',
  );
}
